name: Node CI (Shared)
on:
  workflow_call:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 18
      - run: npm install || true
      - run: npm test --if-present
